Task 5
goaliepash/FindYourJob pull request #14
Opened 2024-02-18 12:39 UTC by Dassenka

Созданы и реализованы классы:
data class VacancyDto
data class ResponseVacanciesListDto
open class Response
data class RequestVacanciesListSearch
data class RequestVacancySearch
data class RequestSimilarVacancySearch
interface NetworkClient
interface HHApiService
 class RetrofitNetworkClient

Не реализованы дата классы и запросы для фильтров (лучше вынести в отдельный таск и PR из-за объема)

2024-02-18 15:07 UTC, goaliepash commented on app/src/main/java/ru/practicum/android/diploma/data/network/HHApiService.kt
> +    // suspend fun getIndustries(): Response<List<CountriesDTO>>
Каменты лучше не оставлять в PR.

2024-02-19 09:51 UTC, AleksandrRegulus requested changes

2024-02-19 09:51 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/dto/ResponseVacanciesListDto.kt
> +    val gross: Boolean,
Кажется для списка этот параметр не нужен
gross это Признак что границы зарплаты указаны до вычета налогов

2024-02-19 09:51 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
> +    val gross: Boolean,
На сколько я увидел в дизайне эта инфа не используется
(Признак что границы зарплаты указаны до вычета налогов)

2024-02-19 09:51 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
> +    val comment: String,
Не вижу такой параметр в API

2024-02-19 09:51 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
> +    val schedule: ScheduleResponseDto,
"Название графика работы" например "полный день"
То же не увидел в макетах где это может нам пригодиться.

2024-02-19 09:51 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
> +    val comment: String,
А вот по поводу этого параметра я в некотором ступоре. 
С одной стороны в макетах его нет, т.е. нужен ли не понятно.
С другой стороны в макете в разделе контакты есть "комментарий" "заполнить анкету по форме..."
Но, данный параметр, согласно API "удобное время для звонка по этому номеру" и относится к каждому тел номеру, т.е. у каждого может быть разный камент или не быть вовсе. 
В макете же камент общий для раздела Контакты. 
Но у сущности contacts нет такого поля...
И у всей вакансии нет такого поля...

2024-02-19 15:46 UTC, Dassenka commented on app/src/main/java/ru/practicum/android/diploma/data/dto/ResponseVacanciesListDto.kt
> +    val page: Int,
По логике предлагаемой в теории Практикума расписан вариант действий и если я правильно поняла там рализация логика без участия per_page. Главное передать его в запросе 
![Screenshot_20240219_184039_Yandex Start](https://github.com/goaliepash/FindYourJob/assets/118569191/02439a7d-c3c9-48a9-87c6-18954f8bdde2)

2024-02-19 15:49 UTC, Dassenka commented on app/src/main/java/ru/practicum/android/diploma/data/dto/ResponseVacanciesListDto.kt
> +    val gross: Boolean,
Не обратила внимания, удалю 👍

2024-02-19 15:56 UTC, Dassenka commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
> +    val comment: String,
Перепроверила, ты прав. Видимо после предварительной наметки класса, сделанному по макету, забыла удалить.

2024-02-19 16:02 UTC, Dassenka commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
> +    val schedule: ScheduleResponseDto,
Я подумала, что это указывается вот тут, после занятости.
![Screenshot_20240219_185923_Yandex Start](https://github.com/goaliepash/FindYourJob/assets/118569191/b42eab16-ba8b-4665-9471-fe1bb0d32ac4)

2024-02-19 16:03 UTC, Dassenka commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
> +    val gross: Boolean,
Удалю

2024-02-19 16:05 UTC, Dassenka commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
> +    val comment: String,
Исходя из этой же логики я и оставила это поле до прояснения ситуации ))

2024-02-19 16:07 UTC, Dassenka commented on app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
> +                    val response = hhApiService.searchVacancies(options.mapValues { dto.toString() })
В корутину обернут весь return (в самом верху в начале функции)

2024-02-19 16:11 UTC, Dassenka commented on app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
> +                }
Блок else требует студия из-за того, что вся функция завернута в return.

2024-02-19 16:13 UTC, Dassenka commented on app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
> +        ) as ConnectivityManager
Подскажи пожалуйста как это выглядит?

2024-02-19 18:23 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
> +                }
Точно! Не доглядел)

2024-02-19 18:24 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
> +                    val response = hhApiService.searchVacancies(options.mapValues { dto.toString() })
И опять недоглядел)

2024-02-19 18:26 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/dto/ResponseVacanciesListDto.kt
> +    val page: Int,
Тогда ок. Им виднее)

2024-02-19 18:28 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyDto.kt
> +    val schedule: ScheduleResponseDto,
Вполне может быть.. Это мы узнаем когда начнем делать запросы.

2024-02-19 18:32 UTC, AleksandrRegulus commented on app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
> +            }
По сути, как я вижу
```
if (dto !is RequestVacancySearch) {
                Response<Any>().apply { resultCode = BAD_REQUEST }
            }
``` 
И 
```
else -> {
                    Response<Any>().apply { resultCode = UNEXPECTED_ERROR }
                }
```
Выполнятся только если мы передали в dto не то, что ожидаем. И с ответом от сервера это не связано.

2024-02-19 20:37 UTC, AleksandrRegulus approved these changes

2024-02-19 20:38 UTC, goaliepash approved these changes

2024-02-19 20:39 UTC, merged